import { getCommits } from "@/helpers/api-commits";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home({ commitList }: any) {
	const [commits, setCommits] = useState([]);
	const [isLoading, setLoading] = useState(false);

	useEffect(() => {
		setCommits(commitList);
	}, [commitList]);

	const refreshCommits = async () => {
		setLoading(true);

		const commitList = await getCommits();

		setCommits(commitList);
		setLoading(false);
	};

	return (
		<>
			<Head>
				<title>Test App for Immigrant Invest</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				{commits.map((commit: any) => (
					<p key={commit.url}>{commit.url}</p>
				))}
				<button onClick={refreshCommits} disabled={isLoading}>
					{isLoading ? "Loading..." : "Refresh"}
				</button>
			</main>
		</>
	);
}

export async function getStaticProps() {
	const commitList = await getCommits();
	return {
		props: { commitList },
		revalidate: 10 * 60,
	};
}
